<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Cart_Management.ApplicationService</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cart Management.Core\Cart Management.Core.csproj" />
    <ProjectReference Include="..\Cart Management.DataService\Cart Management.DataService.csproj" />
  </ItemGroup>

</Project>
